// Generated by CoffeeScript 1.3.3
(function() {
  var clean, runMe;

  clean = function(type, location, usingSoap) {
    var msg;
    if (type == null) {
      type = "ANIMAL";
    }
    if (location == null) {
      location = "CAGE";
    }
    if (usingSoap == null) {
      usingSoap = true;
    }
    msg = "I am washing the " + type + ", in the " + location;
    if (usingSoap) {
      msg += ", using soap.";
    } else {
      msg += ", without soap.";
    }
    alert(msg);
    return alert("Done!");
  };

  runMe = function() {
    clean("baboon", "pen", false);
    clean("elephant", null, true);
    return clean();
  };

  $(document).ready(function() {
    return $('#btn-run-coffee').on('click', function() {
      return runMe();
    });
  });

}).call(this);
